name: bitcoin-qt
version: '1.0.1.1-git-21e45cb'
summary: Bitcoin Unlimited - The Only Bitcoin Client That Gives You Complete Freedom!
description: |
  Bitcoin is a free open source peer-to-peer electronic cash system that is completely decentralized, without the need for a central server or trusted parties. Users hold the crypto keys to their own money and transact directly with each other, with the help of a P2P network to check for double-spending.

grade: stable
confinement: strict

apps:
  bitcoin-qt:
    command: desktop-launch bitcoin-qt
    plugs: [network, network-bind, home, unity7]

parts:
  libdb4.8:
    plugin: autotools
    source: http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
#    source-checksum: sha256/12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef
    source-subdir: dist
    stage: # we need to copy files to the staging area so that bitcoin can use them when compiling
      - include/*
      - lib/*
    build: |
      cd build_unix
      ../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
    install: |
      cd build_unix
      make install
    prime:
      - -* # we don't need the compiled files in the final snap
  bitcoin-qt:
    after: [libdb4.8, desktop-qt5]
    build-packages: [libdb4.8]
    plugin: autotools
    source: git://github.com/BitcoinUnlimited/BitcoinUnlimited.git
    source-type: git
    source-commit: 21e45cb385d8f60e9ab99b548ab6815d6c7129aa
    build-packages:
      - g++
      - libboost-dev
      - libboost-system-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-thread-dev
      - libboost-test-dev
      - libssl-dev
      - libevent-dev
      - protobuf-compiler
      - libzmq3-dev
      - libminiupnpc-dev
      - libqrencode-dev
    configflags:
       - --with-gui
       - --enable-hardening

